server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://locathost:3306/springboot-vue?useUnicode=ture&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 88888888